name: primjer
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - aom=3.9.1=h7bae524_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=h3ff7a7c_1
  - double-conversion=3.3.1=h286801f_0
  - ffmpeg=7.1.1=gpl_h670d5b4_111
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - gdk-pixbuf=2.44.4=h7542897_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.14=hec049ff_2
  - harfbuzz=12.2.0=haf38c7b_0
  - hdf5=1.14.6=nompi_h51e7c0a_105
  - icu=75.1=hfee45f7_0
  - imath=3.2.1=hf787086_0
  - jasper=4.2.8=hc0e5025_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libasprintf=0.25.1=h493aca8_0
  - libass=0.17.4=hcbd7ca7_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.11.0=5_h51639a9_openblas
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libclang-cpp19.1=19.1.7=default_hf3020a7_7
  - libclang13=21.1.8=default_h13b06bd_1
  - libcurl=8.18.0=he38603e_0
  - libcxx=21.1.8=hf598326_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgettextpo=0.25.1=h493aca8_0
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libglib=2.86.2=he69a767_0
  - libhwloc=2.12.2=default_ha3cc4f2_1000
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblapacke=3.11.0=5_h1b118fd_openblas
  - libllvm19=19.1.7=h8e0c9ce_2
  - libllvm21=21.1.8=h8e0c9ce_0
  - liblzma=5.8.2=h8088a28_0
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_4
  - libopencv=4.12.0=qt6_py39hae564cd_602
  - libopenvino=2025.2.0=h56e7ac4_1
  - libopenvino-arm-cpu-plugin=2025.2.0=h56e7ac4_1
  - libopenvino-auto-batch-plugin=2025.2.0=he81eb65_1
  - libopenvino-auto-plugin=2025.2.0=he81eb65_1
  - libopenvino-hetero-plugin=2025.2.0=h273c05f_1
  - libopenvino-ir-frontend=2025.2.0=h273c05f_1
  - libopenvino-onnx-frontend=2025.2.0=h6386500_1
  - libopenvino-paddle-frontend=2025.2.0=h6386500_1
  - libopenvino-pytorch-frontend=2025.2.0=hec049ff_1
  - libopenvino-tensorflow-frontend=2025.2.0=hee62d61_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hec049ff_1
  - libopus=1.6.1=h1a92334_0
  - libpng=1.6.54=h132b30e_0
  - libpq=18.1=h944245b_2
  - libprotobuf=6.31.1=h98f38fd_4
  - librsvg=2.60.0=h5c55ec3_0
  - libsqlite=3.51.2=h1b79a29_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h7dc4979_0
  - libusb=1.0.29=hbc156a2_0
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - ncurses=6.5=h5e97a16_3
  - numpy=1.23.5=py39hefdcf20_0
  - opencv=4.12.0=qt6_py39h0415320_602
  - openexr=3.3.5=hc05139d_1
  - openh264=2.6.0=hb5b2745_0
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.0=h5503f6c_0
  - pango=1.56.4=h875632e_0
  - pcre2=10.46=h7125dd6_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - pugixml=1.15=hd3d436d_0
  - py-opencv=4.12.0=qt6_py39h7ddf7b3_602
  - python=3.9.23=h7139b31_0_cpython
  - python_abi=3.9=8_cp39
  - qt6-main=6.9.3=hb266e41_0
  - rav1e=0.7.1=h0716509_3
  - readline=8.3=h46df422_0
  - scikit-learn=1.6.1=py39h451895d_0
  - scipy=1.13.1=py39h3d5391c_0
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.30=h6fa9c73_0
  - setuptools=80.9.0=pyhff2d567_0
  - snappy=1.2.2=hada39a4_1
  - svt-av1=3.1.2=h12ba402_0
  - tbb=2022.3.0=h4ddebb9_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_3
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - zstd=1.5.7=hbf9d68e_6

prefix: "/Users/admin/.local/share/mamba/envs/primjer"
