[workspace]
authors = ["Nikola Savic <nikola.savic20@gmail.com>"]
channels = ["conda-forge"]
name = "primjer"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = "1.23.*"
scikit-learn = ">=1.6.1,<2"
opencv = ">=4.12.0,<5"
python = "3.9.*"
